/** 平台侧审计动作机器码，前端筛选下拉与落库共用同一份。 */
export const AuditAction = {
  MerchantCreate: 'merchant.create',
  MerchantUpdate: 'merchant.update',
  MerchantStatus: 'merchant.status',
  AccountCreate: 'account.create',
  AccountUpdate: 'account.update',
  AccountPassword: 'account.password',
  PaymentChannelUpdate: 'payment.channel.update',
  MerchantPaymentAudit: 'payment.merchant.audit',
  MerchantPaymentStatus: 'payment.merchant.status',
  MerchantPaymentApply: 'payment.merchant.apply',
  MerchantProfitShareRate: 'payment.merchant.profit_share_rate',
  PrinterCreate: 'print.printer.create',
  PrinterUpdate: 'print.printer.update',
  PrinterDelete: 'print.printer.delete',
  PrintTaskRetry: 'print.task.retry',
  PrintProviderUpdate: 'print.provider.update',
  SmsConfigUpdate: 'sms.config.update',
  TableCreate: 'table.create',
  TableUpdate: 'table.update',
  TableDelete: 'table.delete',
  /** 重制码会换掉 qr_token，等于作废已贴出去的旧码，必须单独留痕 */
  TableQrRegenerate: 'table.qr_regenerate',
  TableOpen: 'table.open',
  TableClose: 'table.close',
  CashierOrderCreate: 'cashier.order.create',
  MiniProgramConfigUpdate: 'mini_program.config.update',
  PlatformLogin: 'auth.login',
  PlatformLoginFailed: 'auth.login_failed',
  PlatformLogout: 'auth.logout',
  PlatformPasswordChanged: 'auth.password_changed',
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  [AuditAction.MerchantCreate]: '开通商户',
  [AuditAction.MerchantUpdate]: '修改商户资料',
  [AuditAction.MerchantStatus]: '变更商户状态',
  [AuditAction.AccountCreate]: '新增平台账号',
  [AuditAction.AccountUpdate]: '修改平台账号',
  [AuditAction.AccountPassword]: '重置平台账号密码',
  [AuditAction.PaymentChannelUpdate]: '修改支付渠道配置',
  [AuditAction.MerchantPaymentAudit]: '审核商户支付进件',
  [AuditAction.MerchantPaymentStatus]: '启停商户支付渠道',
  [AuditAction.MerchantPaymentApply]: '商户提交支付进件',
  [AuditAction.MerchantProfitShareRate]: '调整商户抽佣比例',
  [AuditAction.PrinterCreate]: '新增打印机',
  [AuditAction.PrinterUpdate]: '修改打印机配置',
  [AuditAction.PrinterDelete]: '删除打印机',
  [AuditAction.PrintTaskRetry]: '重试打印任务',
  [AuditAction.PrintProviderUpdate]: '修改云打印机厂商配置',
  [AuditAction.SmsConfigUpdate]: '修改短信配置',
  [AuditAction.TableCreate]: '新增桌位',
  [AuditAction.TableUpdate]: '修改桌位',
  [AuditAction.TableDelete]: '删除桌位',
  [AuditAction.TableQrRegenerate]: '重新生成桌位二维码',
  [AuditAction.TableOpen]: '开台',
  [AuditAction.TableClose]: '清台',
  [AuditAction.CashierOrderCreate]: '收银台线下点餐',
  [AuditAction.MiniProgramConfigUpdate]: '修改小程序配置',
  [AuditAction.PlatformLogin]: '平台登录',
  [AuditAction.PlatformLoginFailed]: '平台登录失败',
  [AuditAction.PlatformLogout]: '平台退出登录',
  [AuditAction.PlatformPasswordChanged]: '平台账号修改密码',
};

export const AuditTargetType = {
  Merchant: 'merchant',
  Account: 'account',
  Auth: 'auth',
  MiniProgram: 'mini_program',
  PaymentChannel: 'payment_channel',
  MerchantPayment: 'merchant_payment',
  Printer: 'printer',
  PrintTask: 'print_task',
  PrintProvider: 'print_provider',
  SmsConfig: 'sms_config',
  Table: 'table',
  Order: 'order',
} as const;
export type AuditTargetType = (typeof AuditTargetType)[keyof typeof AuditTargetType];

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action as AuditAction] ?? action;
}
